<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by lupdate-zig. To update this file, run the 'lupdate-zig' command below. -->
<!-- lupdate-zig -i "main.zig" -o "lupdate_en.ts" -l "en_US" -->
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>Main</name>
    <message>
        <location filename="main.zig" line="113"/>
        <source>L&amp;anguage:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="117"/>
        <source>&amp;Up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="121"/>
        <source>&amp;Down</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="125"/>
        <source>&amp;Left</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="129"/>
        <source>&amp;Right</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="133"/>
        <source>E&amp;xit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="137"/>
        <source>&amp;File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="main.zig" line="141"/>
        <source>Ctrl+Q</source>
        <comment>Quit</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
