// Generated by libqt6zig uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-zig' command below.
//
// uic-zig -i design.ui -o design.zig -e

const std = @import("std");
const qt6 = @import("libqt6zig");
const C = qt6.C;

pub const MainWindowUi = struct {
    MainWindow: C.QMainWindow,
    centralwidget: C.QWidget,
    gridLayout: C.QGridLayout,
    keditlistwidget: C.KEditListWidget,
    tabWidget: C.QTabWidget,
    tab: C.QWidget,
    formLayout: C.QFormLayout,
    label: C.QLabel,
    kcombobox: C.KComboBox,
    label_2: C.QLabel,
    kpluralhandlingspinbox: C.KPluralHandlingSpinBox,
    label_3: C.QLabel,
    klineedit: C.KLineEdit,
    tab_2: C.QWidget,
    verticalLayout_2: C.QVBoxLayout,
    verticalLayout_3: C.QVBoxLayout,
    formLayout_2: C.QFormLayout,
    kfontrequester: C.KFontRequester,
    kled: C.KLed,
    menubar: C.QMenuBar,
    menu_File: C.QMenu,
    statusbar: C.QStatusBar,
    dockWidget: C.QDockWidget,
    dockWidgetContents: C.QWidget,
    verticalLayout: C.QVBoxLayout,
    kdatepicker: C.KDatePicker,
    action_New: C.QAction,
    actionE_xit: C.QAction,

    // RetranslateUi reapplies all text translations
    pub fn RetranslateUi(ui: *MainWindowUi, allocator: std.mem.Allocator) void {
        const text0 = qt6.qcoreapplication.Translate("MainWindow", "MainWindow", allocator);
        defer allocator.free(text0);
        qt6.qmainwindow.SetWindowTitle(ui.MainWindow, text0);
        const text1 = qt6.qcoreapplication.Translate("MainWindow", "&New...", allocator);
        defer allocator.free(text1);
        qt6.qaction.SetText(ui.action_New, text1);
        const text2 = qt6.qcoreapplication.Translate("MainWindow", "E&xit", allocator);
        defer allocator.free(text2);
        qt6.qaction.SetText(ui.actionE_xit, text2);
        const text3 = qt6.qcoreapplication.Translate("MainWindow", "Ctrl+Q", allocator);
        defer allocator.free(text3);
        const actionE_xitShortcut = qt6.qkeysequence.New2(text3);
        defer qt6.qkeysequence.Delete(actionE_xitShortcut);
        qt6.qaction.SetShortcut(ui.actionE_xit, actionE_xitShortcut);
        const keditlistwidget_items0 = qt6.qcoreapplication.Translate("MainWindow", "Item 1", allocator);
        defer allocator.free(keditlistwidget_items0);
        const keditlistwidget_items1 = qt6.qcoreapplication.Translate("MainWindow", "Item 2", allocator);
        defer allocator.free(keditlistwidget_items1);
        const keditlistwidget_items2 = qt6.qcoreapplication.Translate("MainWindow", "Item 3", allocator);
        defer allocator.free(keditlistwidget_items2);
        const keditlistwidget_items = [_][]const u8{ keditlistwidget_items0, keditlistwidget_items1, keditlistwidget_items2 };
        qt6.keditlistwidget.SetItems(ui.keditlistwidget, &keditlistwidget_items, allocator);
        const text4 = qt6.qcoreapplication.Translate("MainWindow", "Tab 1", allocator);
        defer allocator.free(text4);
        qt6.qtabwidget.SetTabText(ui.tabWidget, qt6.qtabwidget.IndexOf(ui.tabWidget, ui.tab), text4);
        const text5 = qt6.qcoreapplication.Translate("MainWindow", "Dropdown:", allocator);
        defer allocator.free(text5);
        qt6.qlabel.SetText(ui.label, text5);
        const text6 = qt6.qcoreapplication.Translate("MainWindow", "First", allocator);
        defer allocator.free(text6);
        qt6.kcombobox.SetItemText(ui.kcombobox, 0, text6);
        const text7 = qt6.qcoreapplication.Translate("MainWindow", "Second", allocator);
        defer allocator.free(text7);
        qt6.kcombobox.SetItemText(ui.kcombobox, 1, text7);
        const text8 = qt6.qcoreapplication.Translate("MainWindow", "Number:", allocator);
        defer allocator.free(text8);
        qt6.qlabel.SetText(ui.label_2, text8);
        const text9 = qt6.qcoreapplication.Translate("MainWindow", "Input:", allocator);
        defer allocator.free(text9);
        qt6.qlabel.SetText(ui.label_3, text9);
        const text10 = qt6.qcoreapplication.Translate("MainWindow", "Tab 2", allocator);
        defer allocator.free(text10);
        qt6.qtabwidget.SetTabText(ui.tabWidget, qt6.qtabwidget.IndexOf(ui.tabWidget, ui.tab_2), text10);
        const text11 = qt6.qcoreapplication.Translate("MainWindow", "Sample text", allocator);
        defer allocator.free(text11);
        qt6.kfontrequester.SetSampleText(ui.kfontrequester, text11);
        const text12 = qt6.qcoreapplication.Translate("MainWindow", "&File", allocator);
        defer allocator.free(text12);
        qt6.qmenu.SetTitle(ui.menu_File, text12);
        const text13 = qt6.qcoreapplication.Translate("MainWindow", "Dock Title", allocator);
        defer allocator.free(text13);
        qt6.qdockwidget.SetWindowTitle(ui.dockWidget, text13);
    }
};

// NewMainWindowUi creates all the Qt objects for MainWindowUi
pub fn NewMainWindowUi(allocator: std.mem.Allocator) !*MainWindowUi {
    var ui = try allocator.create(MainWindowUi);

    ui.MainWindow = qt6.qmainwindow.New2();
    qt6.qmainwindow.SetObjectName(ui.MainWindow, "MainWindow");
    qt6.qmainwindow.Resize(ui.MainWindow, 800, 600);

    ui.action_New = qt6.qaction.New4(ui.MainWindow);
    qt6.qaction.SetObjectName(ui.action_New, "action_New");

    ui.actionE_xit = qt6.qaction.New4(ui.MainWindow);
    qt6.qaction.SetObjectName(ui.actionE_xit, "actionE_xit");

    ui.centralwidget = qt6.qwidget.New(ui.MainWindow);
    qt6.qwidget.SetObjectName(ui.centralwidget, "centralwidget");

    ui.gridLayout = qt6.qgridlayout.New(ui.centralwidget);
    qt6.qgridlayout.SetObjectName(ui.gridLayout, "gridLayout");

    ui.keditlistwidget = qt6.keditlistwidget.New(ui.centralwidget);
    qt6.keditlistwidget.SetObjectName(ui.keditlistwidget, "keditlistwidget");
    qt6.qgridlayout.AddWidget2(ui.gridLayout, ui.keditlistwidget, 0, 1);

    ui.tabWidget = qt6.qtabwidget.New(ui.centralwidget);
    qt6.qtabwidget.SetObjectName(ui.tabWidget, "tabWidget");

    ui.tab = qt6.qwidget.New2();
    qt6.qwidget.SetObjectName(ui.tab, "tab");

    ui.formLayout = qt6.qformlayout.New(ui.tab);
    qt6.qformlayout.SetObjectName(ui.formLayout, "formLayout");

    ui.label = qt6.qlabel.New(ui.tab);
    qt6.qlabel.SetObjectName(ui.label, "label");
    qt6.qformlayout.SetWidget(ui.formLayout, 0, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label);

    ui.kcombobox = qt6.kcombobox.New(ui.tab);
    qt6.kcombobox.SetObjectName(ui.kcombobox, "kcombobox");
    qt6.kcombobox.AddItem(ui.kcombobox, "");
    qt6.kcombobox.AddItem(ui.kcombobox, "");
    qt6.qformlayout.SetWidget(ui.formLayout, 0, qt6.qformlayout_enums.ItemRole.FieldRole, ui.kcombobox);

    ui.label_2 = qt6.qlabel.New(ui.tab);
    qt6.qlabel.SetObjectName(ui.label_2, "label_2");
    qt6.qformlayout.SetWidget(ui.formLayout, 1, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label_2);

    ui.kpluralhandlingspinbox = qt6.kpluralhandlingspinbox.New(ui.tab);
    qt6.kpluralhandlingspinbox.SetObjectName(ui.kpluralhandlingspinbox, "kpluralhandlingspinbox");
    qt6.qformlayout.SetWidget(ui.formLayout, 1, qt6.qformlayout_enums.ItemRole.FieldRole, ui.kpluralhandlingspinbox);

    ui.label_3 = qt6.qlabel.New(ui.tab);
    qt6.qlabel.SetObjectName(ui.label_3, "label_3");
    qt6.qformlayout.SetWidget(ui.formLayout, 2, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label_3);

    ui.klineedit = qt6.klineedit.New(ui.tab);
    qt6.klineedit.SetObjectName(ui.klineedit, "klineedit");
    qt6.qformlayout.SetWidget(ui.formLayout, 2, qt6.qformlayout_enums.ItemRole.FieldRole, ui.klineedit);

    _ = qt6.qtabwidget.AddTab(ui.tabWidget, ui.tab, "");

    ui.tab_2 = qt6.qwidget.New2();
    qt6.qwidget.SetObjectName(ui.tab_2, "tab_2");

    ui.verticalLayout_2 = qt6.qvboxlayout.New(ui.tab_2);
    qt6.qvboxlayout.SetObjectName(ui.verticalLayout_2, "verticalLayout_2");

    ui.verticalLayout_3 = qt6.qvboxlayout.New2();
    qt6.qvboxlayout.SetObjectName(ui.verticalLayout_3, "verticalLayout_3");

    ui.formLayout_2 = qt6.qformlayout.New2();
    qt6.qformlayout.SetObjectName(ui.formLayout_2, "formLayout_2");

    ui.kfontrequester = qt6.kfontrequester.New(ui.tab_2);
    qt6.kfontrequester.SetObjectName(ui.kfontrequester, "kfontrequester");
    qt6.qformlayout.SetWidget(ui.formLayout_2, 0, qt6.qformlayout_enums.ItemRole.LabelRole, ui.kfontrequester);

    qt6.qvboxlayout.AddLayout(ui.verticalLayout_3, ui.formLayout_2);

    ui.kled = qt6.kled.New(ui.tab_2);
    qt6.kled.SetObjectName(ui.kled, "kled");
    qt6.kled.SetMinimumSize2(ui.kled, 40, 40);
    qt6.kled.SetMaximumSize2(ui.kled, 50, 50);
    qt6.kled.SetShape(ui.kled, qt6.kled_enums.Shape.Circular);
    const kled_color0 = qt6.qcolor.New5(236, 145, 92);
    defer qt6.qcolor.Delete(kled_color0);
    qt6.kled.SetColor(ui.kled, kled_color0);

    qt6.qvboxlayout.AddWidget(ui.verticalLayout_3, ui.kled);

    qt6.qvboxlayout.AddLayout(ui.verticalLayout_2, ui.verticalLayout_3);

    _ = qt6.qtabwidget.AddTab(ui.tabWidget, ui.tab_2, "");
    qt6.qgridlayout.AddWidget2(ui.gridLayout, ui.tabWidget, 0, 0);

    qt6.qmainwindow.SetCentralWidget(ui.MainWindow, ui.centralwidget);

    ui.menubar = qt6.qmenubar.New(ui.MainWindow);
    qt6.qmenubar.SetObjectName(ui.menubar, "menubar");
    qt6.qmenubar.SetGeometry(ui.menubar, 0, 0, 800, 27);

    ui.menu_File = qt6.qmenu.New(ui.menubar);
    qt6.qmenu.SetObjectName(ui.menu_File, "menu_File");
    qt6.qmainwindow.SetMenuBar(ui.MainWindow, ui.menubar);

    ui.statusbar = qt6.qstatusbar.New(ui.MainWindow);
    qt6.qstatusbar.SetObjectName(ui.statusbar, "statusbar");
    qt6.qmainwindow.SetStatusBar(ui.MainWindow, ui.statusbar);

    ui.dockWidget = qt6.qdockwidget.New(ui.MainWindow);
    qt6.qdockwidget.SetObjectName(ui.dockWidget, "dockWidget");
    qt6.qmainwindow.AddDockWidget(ui.MainWindow, 1, ui.dockWidget); // qt6.qnamespace_enums.DockWidgetArea (1)

    ui.dockWidgetContents = qt6.qwidget.New2();
    qt6.qwidget.SetObjectName(ui.dockWidgetContents, "dockWidgetContents");

    ui.verticalLayout = qt6.qvboxlayout.New(ui.dockWidgetContents);
    qt6.qvboxlayout.SetObjectName(ui.verticalLayout, "verticalLayout");

    ui.kdatepicker = qt6.kdatepicker.New(ui.dockWidgetContents);
    qt6.kdatepicker.SetObjectName(ui.kdatepicker, "kdatepicker");

    qt6.qvboxlayout.AddWidget(ui.verticalLayout, ui.kdatepicker);
    qt6.qdockwidget.SetWidget(ui.dockWidget, ui.dockWidgetContents);

    qt6.qmenubar.AddAction(ui.menubar, qt6.qmenu.MenuAction(ui.menu_File));
    qt6.qmenu.AddAction(ui.menu_File, ui.action_New);
    _ = qt6.qmenu.AddSeparator(ui.menu_File);
    qt6.qmenu.AddAction(ui.menu_File, ui.actionE_xit);

    ui.RetranslateUi(allocator);

    qt6.qtabwidget.SetCurrentIndex(ui.tabWidget, 0);

    return ui;
}
