// Generated by libqt6zig uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-zig' command below.
//
// uic-zig -i design.ui -o design.zig -e

const std = @import("std");
const qt6 = @import("libqt6zig");

/// The type definition for MainWindowUi containing all of the Qt objects
pub const MainWindowUi = struct {
    MainWindow: qt6.QMainWindow = undefined,
    centralwidget: qt6.QWidget = undefined,
    gridLayout: qt6.QGridLayout = undefined,
    keditlistwidget: qt6.KEditListWidget = undefined,
    tabWidget: qt6.QTabWidget = undefined,
    tab: qt6.QWidget = undefined,
    formLayout: qt6.QFormLayout = undefined,
    label: qt6.QLabel = undefined,
    kcombobox: qt6.KComboBox = undefined,
    label_2: qt6.QLabel = undefined,
    kpluralhandlingspinbox: qt6.KPluralHandlingSpinBox = undefined,
    label_3: qt6.QLabel = undefined,
    klineedit: qt6.KLineEdit = undefined,
    tab_2: qt6.QWidget = undefined,
    verticalLayout_2: qt6.QVBoxLayout = undefined,
    verticalLayout_3: qt6.QVBoxLayout = undefined,
    formLayout_2: qt6.QFormLayout = undefined,
    kfontrequester: qt6.KFontRequester = undefined,
    kled: qt6.KLed = undefined,
    menubar: qt6.QMenuBar = undefined,
    menu_File: qt6.QMenu = undefined,
    statusbar: qt6.QStatusBar = undefined,
    dockWidget: qt6.QDockWidget = undefined,
    dockWidgetContents: qt6.QWidget = undefined,
    verticalLayout: qt6.QVBoxLayout = undefined,
    kdatepicker: qt6.KDatePicker = undefined,
    action_New: qt6.QAction = undefined,
    actionE_xit: qt6.QAction = undefined,

    /// Initialize all of the Qt objects for MainWindowUi
    ///
    /// ## Parameters:
    ///
    /// ` ui: *MainWindowUi `
    ///
    /// ` allocator: std.mem.Allocator `
    ///
    /// ` parent: QWidget ` (can be null)
    ///
    pub fn init(ui: *MainWindowUi, allocator: std.mem.Allocator, parent: anytype) void {
        ui.MainWindow = .new2();
        ui.MainWindow.setObjectName("MainWindow");
        ui.MainWindow.setParent(parent);
        ui.MainWindow.resize(800, 600);

        ui.action_New = .new4(ui.MainWindow);
        ui.action_New.setObjectName("action_New");

        ui.actionE_xit = .new4(ui.MainWindow);
        ui.actionE_xit.setObjectName("actionE_xit");

        ui.centralwidget = .new(ui.MainWindow);
        ui.centralwidget.setObjectName("centralwidget");

        ui.gridLayout = .new(ui.centralwidget);
        ui.gridLayout.setObjectName("gridLayout");

        ui.keditlistwidget = .new(ui.centralwidget);
        ui.keditlistwidget.setObjectName("keditlistwidget");
        ui.gridLayout.addWidget2(ui.keditlistwidget, 0, 1);

        ui.tabWidget = .new(ui.centralwidget);
        ui.tabWidget.setObjectName("tabWidget");

        ui.tab = .new2();
        ui.tab.setObjectName("tab");

        ui.formLayout = .new(ui.tab);
        ui.formLayout.setObjectName("formLayout");

        ui.label = .new(ui.tab);
        ui.label.setObjectName("label");
        ui.formLayout.setWidget(0, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label);

        ui.kcombobox = .new(ui.tab);
        ui.kcombobox.setObjectName("kcombobox");
        ui.kcombobox.addItem("");
        ui.kcombobox.addItem("");
        ui.formLayout.setWidget(0, qt6.qformlayout_enums.ItemRole.FieldRole, ui.kcombobox);

        ui.label_2 = .new(ui.tab);
        ui.label_2.setObjectName("label_2");
        ui.formLayout.setWidget(1, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label_2);

        ui.kpluralhandlingspinbox = .new(ui.tab);
        ui.kpluralhandlingspinbox.setObjectName("kpluralhandlingspinbox");
        ui.formLayout.setWidget(1, qt6.qformlayout_enums.ItemRole.FieldRole, ui.kpluralhandlingspinbox);

        ui.label_3 = .new(ui.tab);
        ui.label_3.setObjectName("label_3");
        ui.formLayout.setWidget(2, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label_3);

        ui.klineedit = .new(ui.tab);
        ui.klineedit.setObjectName("klineedit");
        ui.formLayout.setWidget(2, qt6.qformlayout_enums.ItemRole.FieldRole, ui.klineedit);

        _ = ui.tabWidget.addTab(ui.tab, "");

        ui.tab_2 = .new2();
        ui.tab_2.setObjectName("tab_2");

        ui.verticalLayout_2 = .new(ui.tab_2);
        ui.verticalLayout_2.setObjectName("verticalLayout_2");

        ui.verticalLayout_3 = .new2();
        ui.verticalLayout_3.setObjectName("verticalLayout_3");

        ui.formLayout_2 = .new2();
        ui.formLayout_2.setObjectName("formLayout_2");

        ui.kfontrequester = .new(ui.tab_2);
        ui.kfontrequester.setObjectName("kfontrequester");
        ui.formLayout_2.setWidget(0, qt6.qformlayout_enums.ItemRole.LabelRole, ui.kfontrequester);

        ui.verticalLayout_3.addLayout(ui.formLayout_2);

        ui.kled = .new(ui.tab_2);
        ui.kled.setObjectName("kled");
        ui.kled.setMinimumSize2(40, 40);
        ui.kled.setMaximumSize2(50, 50);
        ui.kled.setShape(qt6.kled_enums.Shape.Circular);
        const kled_color0 = qt6.QColor.new5(236, 145, 92);
        defer kled_color0.delete();
        ui.kled.setColor(kled_color0);

        ui.verticalLayout_3.addWidget(ui.kled);

        ui.verticalLayout_2.addLayout(ui.verticalLayout_3);

        _ = ui.tabWidget.addTab(ui.tab_2, "");
        ui.gridLayout.addWidget2(ui.tabWidget, 0, 0);

        ui.MainWindow.setCentralWidget(ui.centralwidget);

        ui.menubar = .new(ui.MainWindow);
        ui.menubar.setObjectName("menubar");
        ui.menubar.setGeometry(0, 0, 800, 27);

        ui.menu_File = .new(ui.menubar);
        ui.menu_File.setObjectName("menu_File");
        ui.MainWindow.setMenuBar(ui.menubar);

        ui.statusbar = .new(ui.MainWindow);
        ui.statusbar.setObjectName("statusbar");
        ui.MainWindow.setStatusBar(ui.statusbar);

        ui.dockWidget = .new(ui.MainWindow);
        ui.dockWidget.setObjectName("dockWidget");
        ui.MainWindow.addDockWidget(1, ui.dockWidget); // qt6.qnamespace_enums.DockWidgetArea (1)

        ui.dockWidgetContents = .new2();
        ui.dockWidgetContents.setObjectName("dockWidgetContents");

        ui.verticalLayout = .new(ui.dockWidgetContents);
        ui.verticalLayout.setObjectName("verticalLayout");

        ui.kdatepicker = .new(ui.dockWidgetContents);
        ui.kdatepicker.setObjectName("kdatepicker");

        ui.verticalLayout.addWidget(ui.kdatepicker);
        ui.dockWidget.setWidget(ui.dockWidgetContents);

        ui.menubar.addAction(ui.menu_File.menuAction());
        ui.menu_File.addAction(ui.action_New);
        _ = ui.menu_File.addSeparator();
        ui.menu_File.addAction(ui.actionE_xit);

        ui.retranslate(allocator);

        ui.tabWidget.setCurrentIndex(0);
    }

    /// If there is no parent widget, delete the main widget for
    /// MainWindowUi and the child Qt objects
    pub fn deinit(ui: *const MainWindowUi) void {
        if (ui.MainWindow.parentWidget().ptr == null)
            ui.MainWindow.delete();
    }

    /// Reapply all text translations
    pub fn retranslate(ui: *const MainWindowUi, allocator: std.mem.Allocator) void {
        const text0 = qt6.QCoreApplication.translate(allocator, "MainWindow", "MainWindow");
        defer allocator.free(text0);
        ui.MainWindow.setWindowTitle(text0);
        const text1 = qt6.QCoreApplication.translate(allocator, "MainWindow", "&New...");
        defer allocator.free(text1);
        ui.action_New.setText(text1);
        const text2 = qt6.QCoreApplication.translate(allocator, "MainWindow", "E&xit");
        defer allocator.free(text2);
        ui.actionE_xit.setText(text2);
        const text3 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Ctrl+Q");
        defer allocator.free(text3);
        const actionE_xit_shortcut = qt6.QKeySequence.new2(text3);
        defer actionE_xit_shortcut.delete();
        ui.actionE_xit.setShortcut(actionE_xit_shortcut);
        const keditlistwidget_items0 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Item 1");
        defer allocator.free(keditlistwidget_items0);
        const keditlistwidget_items1 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Item 2");
        defer allocator.free(keditlistwidget_items1);
        const keditlistwidget_items2 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Item 3");
        defer allocator.free(keditlistwidget_items2);
        const keditlistwidget_items = [_][]const u8{ keditlistwidget_items0, keditlistwidget_items1, keditlistwidget_items2 };
        ui.keditlistwidget.setItems(allocator, &keditlistwidget_items);
        const text4 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Tab 1");
        defer allocator.free(text4);
        ui.tabWidget.setTabText(ui.tabWidget.indexOf(ui.tab), text4);
        const text5 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Dropdown:");
        defer allocator.free(text5);
        ui.label.setText(text5);
        const text6 = qt6.QCoreApplication.translate(allocator, "MainWindow", "First");
        defer allocator.free(text6);
        ui.kcombobox.setItemText(0, text6);
        const text7 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Second");
        defer allocator.free(text7);
        ui.kcombobox.setItemText(1, text7);
        const text8 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Number:");
        defer allocator.free(text8);
        ui.label_2.setText(text8);
        const text9 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Input:");
        defer allocator.free(text9);
        ui.label_3.setText(text9);
        const text10 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Tab 2");
        defer allocator.free(text10);
        ui.tabWidget.setTabText(ui.tabWidget.indexOf(ui.tab_2), text10);
        const text11 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Sample text");
        defer allocator.free(text11);
        ui.kfontrequester.setSampleText(text11);
        const text12 = qt6.QCoreApplication.translate(allocator, "MainWindow", "&File");
        defer allocator.free(text12);
        ui.menu_File.setTitle(text12);
        const text13 = qt6.QCoreApplication.translate(allocator, "MainWindow", "Dock Title");
        defer allocator.free(text13);
        ui.dockWidget.setWindowTitle(text13);
    }
};
