// Generated by libqt6zig uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-zig' command below.
//
// uic-zig -i design.ui -o design.zig

const std = @import("std");
const qt6 = @import("libqt6zig");

/// The type definition for MainWindowUi containing all of the Qt objects
pub const MainWindowUi = struct {
    MainWindow: qt6.QMainWindow,
    centralwidget: qt6.QWidget,
    gridLayout: qt6.QGridLayout,
    tabWidget: qt6.QTabWidget,
    tab: qt6.QWidget,
    formLayout: qt6.QFormLayout,
    label: qt6.QLabel,
    comboBox: qt6.QComboBox,
    label_2: qt6.QLabel,
    spinBox: qt6.QSpinBox,
    tab_2: qt6.QWidget,
    treeWidget: qt6.QTreeWidget,
    menubar: qt6.QMenuBar,
    menu_File: qt6.QMenu,
    statusbar: qt6.QStatusBar,
    dockWidget: qt6.QDockWidget,
    dockWidgetContents: qt6.QWidget,
    verticalLayout: qt6.QVBoxLayout,
    calendarWidget: qt6.QCalendarWidget,
    action_New: qt6.QAction,
    actionE_xit: qt6.QAction,

    /// Reapplies all text translations
    pub fn retranslate(ui: *MainWindowUi, allocator: std.mem.Allocator) void {
        const text0 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "MainWindow");
        defer allocator.free(text0);
        ui.MainWindow.SetWindowTitle(text0);
        const text1 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "&New...");
        defer allocator.free(text1);
        ui.action_New.SetText(text1);
        const text2 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "E&xit");
        defer allocator.free(text2);
        ui.actionE_xit.SetText(text2);
        const text3 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Ctrl+Q");
        defer allocator.free(text3);
        const actionE_xitShortcut = qt6.QKeySequence.New2(text3);
        defer actionE_xitShortcut.Delete();
        ui.actionE_xit.SetShortcut(actionE_xitShortcut);
        const text4 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Tab 1");
        defer allocator.free(text4);
        ui.tabWidget.SetTabText(ui.tabWidget.IndexOf(ui.tab), text4);
        const text5 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Dropdown:");
        defer allocator.free(text5);
        ui.label.SetText(text5);
        const text6 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "First");
        defer allocator.free(text6);
        ui.comboBox.SetItemText(0, text6);
        const text7 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Second");
        defer allocator.free(text7);
        ui.comboBox.SetItemText(1, text7);
        const text8 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Number:");
        defer allocator.free(text8);
        ui.label_2.SetText(text8);
        const text9 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Tab 2");
        defer allocator.free(text9);
        ui.tabWidget.SetTabText(ui.tabWidget.IndexOf(ui.tab_2), text9);
        const text10 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "&File");
        defer allocator.free(text10);
        ui.menu_File.SetTitle(text10);
        const text11 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Dock Title");
        defer allocator.free(text11);
        ui.dockWidget.SetWindowTitle(text11);
    }

    /// Destroys all the Qt objects for MainWindowUi and frees the allocated memory
    pub fn destroy(ui: *MainWindowUi, allocator: std.mem.Allocator) void {
        ui.MainWindow.Delete();
        allocator.destroy(ui);
    }
};

/// Creates all the Qt objects for MainWindowUi
pub fn create(allocator: std.mem.Allocator) !*MainWindowUi {
    var ui = try allocator.create(MainWindowUi);

    ui.MainWindow = qt6.QMainWindow.New2();
    ui.MainWindow.SetObjectName("MainWindow");
    ui.MainWindow.Resize(800, 600);

    ui.action_New = qt6.QAction.New4(ui.MainWindow);
    ui.action_New.SetObjectName("action_New");

    ui.actionE_xit = qt6.QAction.New4(ui.MainWindow);
    ui.actionE_xit.SetObjectName("actionE_xit");

    ui.centralwidget = qt6.QWidget.New(ui.MainWindow);
    ui.centralwidget.SetObjectName("centralwidget");

    ui.gridLayout = qt6.QGridLayout.New(ui.centralwidget);
    ui.gridLayout.SetObjectName("gridLayout");

    ui.tabWidget = qt6.QTabWidget.New(ui.centralwidget);
    ui.tabWidget.SetObjectName("tabWidget");

    ui.tab = qt6.QWidget.New2();
    ui.tab.SetObjectName("tab");

    ui.formLayout = qt6.QFormLayout.New(ui.tab);
    ui.formLayout.SetObjectName("formLayout");

    ui.label = qt6.QLabel.New(ui.tab);
    ui.label.SetObjectName("label");
    ui.formLayout.SetWidget(0, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label);

    ui.comboBox = qt6.QComboBox.New(ui.tab);
    ui.comboBox.SetObjectName("comboBox");
    ui.comboBox.AddItem("");
    ui.comboBox.AddItem("");
    ui.formLayout.SetWidget(0, qt6.qformlayout_enums.ItemRole.FieldRole, ui.comboBox);

    ui.label_2 = qt6.QLabel.New(ui.tab);
    ui.label_2.SetObjectName("label_2");
    ui.formLayout.SetWidget(1, qt6.qformlayout_enums.ItemRole.LabelRole, ui.label_2);

    ui.spinBox = qt6.QSpinBox.New(ui.tab);
    ui.spinBox.SetObjectName("spinBox");
    ui.formLayout.SetWidget(1, qt6.qformlayout_enums.ItemRole.FieldRole, ui.spinBox);

    _ = ui.tabWidget.AddTab(ui.tab, "");

    ui.tab_2 = qt6.QWidget.New2();
    ui.tab_2.SetObjectName("tab_2");

    _ = ui.tabWidget.AddTab(ui.tab_2, "");
    ui.gridLayout.AddWidget2(ui.tabWidget, 0, 0);

    ui.treeWidget = qt6.QTreeWidget.New(ui.centralwidget);
    ui.treeWidget.SetObjectName("treeWidget");
    ui.treeWidget.SetFrameShape(qt6.qframe_enums.Shape.Panel);
    const ui_treeWidgetItem = qt6.QTreeWidgetItem.New();
    ui.treeWidget.SetHeaderItem(ui_treeWidgetItem);
    ui_treeWidgetItem.SetText(0, "1");
    ui.gridLayout.AddWidget2(ui.treeWidget, 0, 1);

    ui.MainWindow.SetCentralWidget(ui.centralwidget);

    ui.menubar = qt6.QMenuBar.New(ui.MainWindow);
    ui.menubar.SetObjectName("menubar");
    ui.menubar.SetGeometry(0, 0, 800, 27);

    ui.menu_File = qt6.QMenu.New(ui.menubar);
    ui.menu_File.SetObjectName("menu_File");
    ui.MainWindow.SetMenuBar(ui.menubar);

    ui.statusbar = qt6.QStatusBar.New(ui.MainWindow);
    ui.statusbar.SetObjectName("statusbar");
    ui.MainWindow.SetStatusBar(ui.statusbar);

    ui.dockWidget = qt6.QDockWidget.New(ui.MainWindow);
    ui.dockWidget.SetObjectName("dockWidget");
    ui.MainWindow.AddDockWidget(1, ui.dockWidget); // qt6.qnamespace_enums.DockWidgetArea (1)

    ui.dockWidgetContents = qt6.QWidget.New2();
    ui.dockWidgetContents.SetObjectName("dockWidgetContents");

    ui.verticalLayout = qt6.QVBoxLayout.New(ui.dockWidgetContents);
    ui.verticalLayout.SetObjectName("verticalLayout");

    ui.calendarWidget = qt6.QCalendarWidget.New(ui.dockWidgetContents);
    ui.calendarWidget.SetObjectName("calendarWidget");

    ui.verticalLayout.AddWidget(ui.calendarWidget);
    ui.dockWidget.SetWidget(ui.dockWidgetContents);

    ui.menubar.AddAction(ui.menu_File.MenuAction());
    ui.menu_File.AddAction(ui.action_New);
    _ = ui.menu_File.AddSeparator();
    ui.menu_File.AddAction(ui.actionE_xit);

    ui.retranslate(allocator);

    return ui;
}
