// Generated by libqt6zig uic. To update this file, edit the .ui file in
// Qt Creator/Designer, and then run the 'uic-zig' command below.
//
// uic-zig -i mainwindow.ui -o mainwindow.zig

const std = @import("std");
const qt6 = @import("libqt6zig");

/// The type definition for MainWindowUi containing all of the Qt objects
pub const MainWindowUi = struct {
    MainWindow: qt6.QMainWindow,
    centralwidget: qt6.QWidget,
    verticalLayout: qt6.QVBoxLayout,
    plainTextEdit: qt6.QPlainTextEdit,
    gridLayout: qt6.QGridLayout,
    label_5: qt6.QLabel,
    label_3: qt6.QLabel,
    label_4: qt6.QLabel,
    pitch: qt6.QSlider,
    label_6: qt6.QLabel,
    volume: qt6.QSlider,
    language: qt6.QComboBox,
    voice: qt6.QComboBox,
    label: qt6.QLabel,
    label_2: qt6.QLabel,
    rate: qt6.QSlider,
    engine: qt6.QComboBox,
    horizontalLayout: qt6.QHBoxLayout,
    speakButton: qt6.QPushButton,
    pauseButton: qt6.QPushButton,
    resumeButton: qt6.QPushButton,
    stopButton: qt6.QPushButton,
    verticalSpacer: qt6.QSpacerItem,
    statusbar: qt6.QStatusBar,

    /// Reapplies all text translations
    pub fn retranslate(ui: *MainWindowUi, allocator: std.mem.Allocator) void {
        const text0 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "MainWindow");
        defer allocator.free(text0);
        ui.MainWindow.SetWindowTitle(text0);
        const text1 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Hello QtTextToSpeech,\nthis is an example text in English.\n\nQtSpeech is a library that makes text to speech easy with Qt.\nDone, over and out.");
        defer allocator.free(text1);
        ui.plainTextEdit.SetPlainText(text1);
        const text2 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Engine");
        defer allocator.free(text2);
        ui.label_5.SetText(text2);
        const text3 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Pitch:");
        defer allocator.free(text3);
        ui.label_3.SetText(text3);
        const text4 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "&Language:");
        defer allocator.free(text4);
        ui.label_4.SetText(text4);
        const text5 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Voice name:");
        defer allocator.free(text5);
        ui.label_6.SetText(text5);
        const text6 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Rate:");
        defer allocator.free(text6);
        ui.label.SetText(text6);
        const text7 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Volume:");
        defer allocator.free(text7);
        ui.label_2.SetText(text7);
        const text8 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Speak");
        defer allocator.free(text8);
        ui.speakButton.SetText(text8);
        const text9 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Pause");
        defer allocator.free(text9);
        ui.pauseButton.SetText(text9);
        const text10 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Resume");
        defer allocator.free(text10);
        ui.resumeButton.SetText(text10);
        const text11 = qt6.QCoreApplication.Translate(allocator, "MainWindow", "Stop");
        defer allocator.free(text11);
        ui.stopButton.SetText(text11);
    }

    /// Destroys all the Qt objects for MainWindowUi and frees the allocated memory
    pub fn destroy(ui: *MainWindowUi, allocator: std.mem.Allocator) void {
        ui.MainWindow.Delete();
        allocator.destroy(ui);
    }
};

/// Creates all the Qt objects for MainWindowUi
pub fn create(allocator: std.mem.Allocator) !*MainWindowUi {
    var ui = try allocator.create(MainWindowUi);

    ui.MainWindow = qt6.QMainWindow.New2();
    ui.MainWindow.SetObjectName("MainWindow");
    ui.MainWindow.Resize(551, 448);

    ui.centralwidget = qt6.QWidget.New(ui.MainWindow);
    ui.centralwidget.SetObjectName("centralwidget");

    ui.verticalLayout = qt6.QVBoxLayout.New(ui.centralwidget);
    ui.verticalLayout.SetObjectName("verticalLayout");

    ui.plainTextEdit = qt6.QPlainTextEdit.New(ui.centralwidget);
    ui.plainTextEdit.SetObjectName("plainTextEdit");
    const sizePolicy0 = qt6.QSizePolicy.New3();
    defer sizePolicy0.Delete();
    sizePolicy0.SetHorizontalPolicy(qt6.qsizepolicy_enums.Policy.Expanding);
    sizePolicy0.SetVerticalPolicy(qt6.qsizepolicy_enums.Policy.Expanding);
    sizePolicy0.SetHorizontalStretch(0);
    sizePolicy0.SetVerticalStretch(0);
    const plainTextEdit_sp = ui.plainTextEdit.SizePolicy();
    defer plainTextEdit_sp.Delete();
    sizePolicy0.SetHeightForWidth(plainTextEdit_sp.HasHeightForWidth());
    ui.plainTextEdit.SetSizePolicy(sizePolicy0);

    ui.verticalLayout.AddWidget(ui.plainTextEdit);

    ui.gridLayout = qt6.QGridLayout.New2();
    ui.gridLayout.SetObjectName("gridLayout");

    ui.label_5 = qt6.QLabel.New(ui.centralwidget);
    ui.label_5.SetObjectName("label_5");
    const sizePolicy1 = qt6.QSizePolicy.New3();
    defer sizePolicy1.Delete();
    sizePolicy1.SetHorizontalPolicy(qt6.qsizepolicy_enums.Policy.Minimum);
    sizePolicy1.SetVerticalPolicy(qt6.qsizepolicy_enums.Policy.Preferred);
    sizePolicy1.SetHorizontalStretch(0);
    sizePolicy1.SetVerticalStretch(0);
    const label_5_sp = ui.label_5.SizePolicy();
    defer label_5_sp.Delete();
    sizePolicy1.SetHeightForWidth(label_5_sp.HasHeightForWidth());
    ui.label_5.SetSizePolicy(sizePolicy1);
    ui.label_5.SetAlignment(qt6.qnamespace_enums.AlignmentFlag.AlignRight | qt6.qnamespace_enums.AlignmentFlag.AlignTrailing | qt6.qnamespace_enums.AlignmentFlag.AlignVCenter);
    ui.gridLayout.AddWidget2(ui.label_5, 4, 0);

    ui.label_3 = qt6.QLabel.New(ui.centralwidget);
    ui.label_3.SetObjectName("label_3");
    const label_3_sp = ui.label_3.SizePolicy();
    defer label_3_sp.Delete();
    sizePolicy1.SetHeightForWidth(label_3_sp.HasHeightForWidth());
    ui.label_3.SetSizePolicy(sizePolicy1);
    ui.label_3.SetAlignment(qt6.qnamespace_enums.AlignmentFlag.AlignRight | qt6.qnamespace_enums.AlignmentFlag.AlignTrailing | qt6.qnamespace_enums.AlignmentFlag.AlignVCenter);
    ui.gridLayout.AddWidget2(ui.label_3, 3, 0);

    ui.label_4 = qt6.QLabel.New(ui.centralwidget);
    ui.label_4.SetObjectName("label_4");
    const label_4_sp = ui.label_4.SizePolicy();
    defer label_4_sp.Delete();
    sizePolicy1.SetHeightForWidth(label_4_sp.HasHeightForWidth());
    ui.label_4.SetSizePolicy(sizePolicy1);
    ui.label_4.SetAlignment(qt6.qnamespace_enums.AlignmentFlag.AlignRight | qt6.qnamespace_enums.AlignmentFlag.AlignTrailing | qt6.qnamespace_enums.AlignmentFlag.AlignVCenter);
    ui.gridLayout.AddWidget2(ui.label_4, 5, 0);

    ui.pitch = qt6.QSlider.New(ui.centralwidget);
    ui.pitch.SetObjectName("pitch");
    ui.pitch.SetMinimum(-10);
    ui.pitch.SetMaximum(10);
    ui.pitch.SetSingleStep(1);
    ui.pitch.SetOrientation(qt6.qnamespace_enums.Orientation.Horizontal);
    ui.gridLayout.AddWidget2(ui.pitch, 3, 2);

    ui.label_6 = qt6.QLabel.New(ui.centralwidget);
    ui.label_6.SetObjectName("label_6");
    ui.label_6.SetAlignment(qt6.qnamespace_enums.AlignmentFlag.AlignRight | qt6.qnamespace_enums.AlignmentFlag.AlignTrailing | qt6.qnamespace_enums.AlignmentFlag.AlignVCenter);
    ui.gridLayout.AddWidget2(ui.label_6, 6, 0);

    ui.volume = qt6.QSlider.New(ui.centralwidget);
    ui.volume.SetObjectName("volume");
    ui.volume.SetMaximum(100);
    ui.volume.SetSingleStep(5);
    ui.volume.SetPageStep(20);
    ui.volume.SetValue(70);
    ui.volume.SetOrientation(qt6.qnamespace_enums.Orientation.Horizontal);
    ui.gridLayout.AddWidget2(ui.volume, 1, 2);

    ui.language = qt6.QComboBox.New(ui.centralwidget);
    ui.language.SetObjectName("language");
    const sizePolicy2 = qt6.QSizePolicy.New3();
    defer sizePolicy2.Delete();
    sizePolicy2.SetHorizontalPolicy(qt6.qsizepolicy_enums.Policy.Expanding);
    sizePolicy2.SetVerticalPolicy(qt6.qsizepolicy_enums.Policy.Fixed);
    sizePolicy2.SetHorizontalStretch(0);
    sizePolicy2.SetVerticalStretch(0);
    const language_sp = ui.language.SizePolicy();
    defer language_sp.Delete();
    sizePolicy2.SetHeightForWidth(language_sp.HasHeightForWidth());
    ui.language.SetSizePolicy(sizePolicy2);
    ui.gridLayout.AddWidget2(ui.language, 5, 2);

    ui.voice = qt6.QComboBox.New(ui.centralwidget);
    ui.voice.SetObjectName("voice");
    ui.gridLayout.AddWidget2(ui.voice, 6, 2);

    ui.label = qt6.QLabel.New(ui.centralwidget);
    ui.label.SetObjectName("label");
    const label_sp = ui.label.SizePolicy();
    defer label_sp.Delete();
    sizePolicy1.SetHeightForWidth(label_sp.HasHeightForWidth());
    ui.label.SetSizePolicy(sizePolicy1);
    ui.label.SetAlignment(qt6.qnamespace_enums.AlignmentFlag.AlignRight | qt6.qnamespace_enums.AlignmentFlag.AlignTrailing | qt6.qnamespace_enums.AlignmentFlag.AlignVCenter);
    ui.gridLayout.AddWidget2(ui.label, 2, 0);

    ui.label_2 = qt6.QLabel.New(ui.centralwidget);
    ui.label_2.SetObjectName("label_2");
    const label_2_sp = ui.label_2.SizePolicy();
    defer label_2_sp.Delete();
    sizePolicy1.SetHeightForWidth(label_2_sp.HasHeightForWidth());
    ui.label_2.SetSizePolicy(sizePolicy1);
    ui.label_2.SetAlignment(qt6.qnamespace_enums.AlignmentFlag.AlignRight | qt6.qnamespace_enums.AlignmentFlag.AlignTrailing | qt6.qnamespace_enums.AlignmentFlag.AlignVCenter);
    ui.gridLayout.AddWidget2(ui.label_2, 1, 0);

    ui.rate = qt6.QSlider.New(ui.centralwidget);
    ui.rate.SetObjectName("rate");
    ui.rate.SetMinimum(-10);
    ui.rate.SetMaximum(10);
    ui.rate.SetOrientation(qt6.qnamespace_enums.Orientation.Horizontal);
    ui.gridLayout.AddWidget2(ui.rate, 2, 2);

    ui.engine = qt6.QComboBox.New(ui.centralwidget);
    ui.engine.SetObjectName("engine");
    const engine_sp = ui.engine.SizePolicy();
    defer engine_sp.Delete();
    sizePolicy2.SetHeightForWidth(engine_sp.HasHeightForWidth());
    ui.engine.SetSizePolicy(sizePolicy2);
    ui.gridLayout.AddWidget2(ui.engine, 4, 2);

    ui.verticalLayout.AddLayout(ui.gridLayout);

    ui.horizontalLayout = qt6.QHBoxLayout.New2();
    ui.horizontalLayout.SetObjectName("horizontalLayout");

    ui.speakButton = qt6.QPushButton.New(ui.centralwidget);
    ui.speakButton.SetObjectName("speakButton");

    ui.horizontalLayout.AddWidget(ui.speakButton);

    ui.pauseButton = qt6.QPushButton.New(ui.centralwidget);
    ui.pauseButton.SetObjectName("pauseButton");
    ui.pauseButton.SetEnabled(false);

    ui.horizontalLayout.AddWidget(ui.pauseButton);

    ui.resumeButton = qt6.QPushButton.New(ui.centralwidget);
    ui.resumeButton.SetObjectName("resumeButton");
    ui.resumeButton.SetEnabled(false);

    ui.horizontalLayout.AddWidget(ui.resumeButton);

    ui.stopButton = qt6.QPushButton.New(ui.centralwidget);
    ui.stopButton.SetObjectName("stopButton");

    ui.horizontalLayout.AddWidget(ui.stopButton);

    ui.verticalLayout.AddLayout(ui.horizontalLayout);

    ui.verticalSpacer = qt6.QSpacerItem.New4(20, 40, qt6.qsizepolicy_enums.Policy.Minimum, qt6.qsizepolicy_enums.Policy.Expanding);
    ui.verticalLayout.AddItem(ui.verticalSpacer);

    ui.MainWindow.SetCentralWidget(ui.centralwidget);

    ui.statusbar = qt6.QStatusBar.New(ui.MainWindow);
    ui.statusbar.SetObjectName("statusbar");
    ui.MainWindow.SetStatusBar(ui.statusbar);

    ui.label_4.SetBuddy(ui.language);
    qt6.QWidget.SetTabOrder(ui.plainTextEdit, ui.speakButton);
    qt6.QWidget.SetTabOrder(ui.speakButton, ui.pauseButton);
    qt6.QWidget.SetTabOrder(ui.pauseButton, ui.resumeButton);
    qt6.QWidget.SetTabOrder(ui.resumeButton, ui.stopButton);

    ui.retranslate(allocator);

    return ui;
}
